const KEY = 'kino-nox-lite-v1';
const seed = {
  movies: [
    {id:1,title:'Neona pilsēta',genre:'Trilleris',year:2026,duration:118,age:'16+',language:'Angļu',subtitles:'Latviešu',price:8.5,accent:"url('assets/poster-neona-pilseta.png')",description:'Pēc nakts lietus Rīga iemirdzas neona krāsās. Detektīve Mara atrod pavedienu, kas ved pāri pilsētai un pašai sev pāri.'},
    {id:2,title:'Mēness arhīvs',genre:'Zinātniskā fantastika',year:2026,duration:132,age:'12+',language:'Angļu',subtitles:'Latviešu',price:9,accent:"url('assets/poster-meness-arhivs.png')",description:'Uz pamestas Mēness stacijas atstāta balss ieraksta atklāj stāstu, kuru neviens nebija paredzējis dzirdēt.'},
    {id:3,title:'Vasaras otra puse',genre:'Drāma',year:2025,duration:104,age:'7+',language:'Latviešu',subtitles:'Angļu',price:7.5,accent:"url('assets/poster-vasaras-otra-puse.png')",description:'Draudzība, kas sākas vienā vasarā, iemāca pieaugt daudz ātrāk nekā gribētos.'},
    {id:4,title:'Savvaļas signāls',genre:'Piedzīvojumu',year:2025,duration:96,age:'7+',language:'Latviešu',subtitles:'Nav',price:7.5,accent:"url('assets/poster-savvalas-signals.png')",description:'Jauna biologu komanda seko noslēpumainam radiosignālam dziļi mežā.'}
  ],
  screenings: [
    {id:1,movieId:1,time:'18:30',hall:'Zāle 1',price:8.5},{id:2,movieId:1,time:'21:15',hall:'Zāle 2',price:9.5},{id:3,movieId:2,time:'19:10',hall:'Zāle 3',price:9},{id:4,movieId:2,time:'22:00',hall:'Zāle 1',price:10},{id:5,movieId:3,time:'17:45',hall:'Zāle 2',price:7.5},{id:6,movieId:4,time:'16:20',hall:'Zāle 1',price:7.5}
  ],
  halls:{'Zāle 1':{rows:6,seats:10},'Zāle 2':{rows:5,seats:8},'Zāle 3':{rows:7,seats:12}},
  reserved:{1:['A2','C7'],2:['B4'],3:['A1','A2','D5'],4:['C3'],5:['B6'],6:['E8']},
  users:[],orders:[],promos:{BLEGH:10},profile:null
};
let state=load();let view={screen:'catalog',movieId:null,screeningId:null,seats:[],cart:null,filter:'Visi',notice:null};
const app=document.querySelector('#app');
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{return {...clone(seed),...JSON.parse(localStorage.getItem(KEY))}}catch{return clone(seed)}}function save(){localStorage.setItem(KEY,JSON.stringify(state));updateCart()}function money(n){return new Intl.NumberFormat('lv-LV',{style:'currency',currency:'EUR'}).format(n)}function today(){return new Intl.DateTimeFormat('lv-LV',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}
function movie(id){return state.movies.find(x=>x.id===Number(id))}function screening(id){return state.screenings.find(x=>x.id===Number(id))}function reserved(id){return state.reserved[id]||[]}function titleArt(m){return m.title.replace(' ','\n')}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2800)}
function updateCart(){document.querySelector('#cart-count').textContent=state.orders.length}
function nav(screen){view={screen,movieId:null,screeningId:null,seats:[],cart:null,filter:view.filter,notice:null};render();app.focus()}
function catalog(){const genres=['Visi',...new Set(state.movies.map(x=>x.genre))];const items=state.movies.filter(m=>view.filter==='Visi'||m.genre===view.filter);return `<section><div class="catalog-hero"><div><p class="eyebrow">${today()}</p><h1 class="page-title">Atrodi savu nākamo seansu.</h1><p class="lede">KINO NOX Lite ir lokāla mācību sistēma. Dati paliek šajā pārlūkā.</p></div></div><div class="utility-row"><div class="filters">${genres.map(g=>`<button class="${g===view.filter?'active':''}" data-filter="${g}">${g}</button>`).join('')}</div><span class="meta">${items.length} filmas</span></div><div class="movie-grid">${items.map(m=>`<article class="movie" data-movie="${m.id}"><div class="poster" style="--poster:${m.accent}">${titleArt(m).replace('\n','<br>')}</div><h2>${m.title}</h2><div class="meta">${m.genre} · ${m.year} · ${m.duration} min</div><div class="price">No ${money(m.price)}</div></article>`).join('')}</div></section>`}
function movieDetail(){const m=movie(view.movieId);const shows=state.screenings.filter(x=>x.movieId===m.id);return `<section class="detail-layout"><div><div class="detail-poster" style="--poster:${m.accent}">${titleArt(m).replace('\n','<br>')}</div></div><div class="detail-copy"><button class="subtle" data-nav="catalog">← Atpakaļ uz katalogu</button><p class="eyebrow">${m.genre}</p><h1>${m.title}</h1><div class="facts"><span>${m.year}</span><span>${m.duration} min</span><span>${m.age}</span><span>${m.language}</span><span>Subtitri: ${m.subtitles}</span></div><p>${m.description}</p><div class="panel"><h2>Šodienas seansi</h2>${shows.map(s=>`<div class="showtime"><div><strong>${s.time}</strong><div class="meta">${s.hall} · no ${money(s.price)}</div></div><button class="button" data-show="${s.id}">Izvēlēties</button></div>`).join('')}</div></div></section>`}
function booking(){const s=screening(view.screeningId),m=movie(s.movieId),hall=state.halls[s.hall];const rows='ABCDEFG'.slice(0,hall.rows).split('');const seatRows=rows.map(r=>`<div class="seat-row" style="--seats:${hall.seats}"><span class="row-label">${r}</span>${Array.from({length:hall.seats},(_,i)=>{let n=`${r}${i+1}`,taken=reserved(s.id).includes(n),selected=view.seats.includes(n);return `<button class="seat ${taken?'taken':''} ${selected?'selected':''}" data-seat="${n}" ${taken?'disabled':''}>${i+1}</button>`}).join('')}</div>`).join('');const subtotal=view.seats.length*s.price;return `<section><button class="subtle" data-movie="${m.id}">← ${m.title}</button><div class="booking-layout"><div><p class="eyebrow">${m.title} · ${s.time} · ${s.hall}</p><h1 class="page-title">Izvēlies vietas.</h1><div class="screen">EKRĀNS</div><div class="seat-map">${seatRows}</div><div class="legend"><span><i></i>Brīva</span><span><i class="taken"></i>Aizņemta</span><span><i class="selected"></i>Izvēlēta</span></div></div><aside class="panel"><h2>Pasūtījums</h2><div class="summary-row"><span>Seanss</span><strong>${s.time}</strong></div><div class="summary-row"><span>Vietas</span><strong>${view.seats.length?view.seats.join(', '):'Nav izvēlētas'}</strong></div><div class="summary-row"><span>Cena par vietu</span><strong>${money(s.price)}</strong></div><div class="summary-row total"><span>Kopā</span><span>${money(subtotal)}</span></div><div class="form-actions"><button class="button" data-action="add-cart" ${view.seats.length?'':'disabled'}>Turpināt uz grozu</button></div>${view.notice?notice(view.notice):''}</aside></div></section>`}
function cart(){const c=view.cart; if(!c)return `<section><p class="eyebrow">Grozs</p><h1 class="page-title">Grozs ir tukšs.</h1><p class="lede">Izvēlieties filmu, seansu un vietas.</p><button class="button" data-nav="catalog">Skatīt filmas</button></section>`;const m=movie(c.movieId),s=screening(c.screeningId);const promo=c.promo||'',discount=state.promos[promo.toUpperCase()]||0,total=c.subtotal*(1-discount/100);return `<section class="booking-layout"><div><p class="eyebrow">Pirkuma apstiprināšana</p><h1 class="page-title">${m.title}</h1><p class="lede">${s.time} · ${s.hall} · vietas ${c.seats.join(', ')}</p><div class="panel"><h2>Atlaides kods</h2><div class="form-actions"><input id="promo" value="${promo}" placeholder="Piemēram, BLEGH"><button class="button secondary" data-action="promo">Piemērot</button></div>${promo?notice(discount?`Atlaide ${discount}% ir piemērota.`:'Nederīgs atlaides kods.',discount?'success':'error'):''}</div><div class="panel"><h2>Saņemšanas veids</h2><p class="meta">Biļete tiks parādīta uzreiz ekrānā. Tā ir mācību simulācija, nevis e-pasta nosūtīšana.</p></div></div><aside class="panel"><h2>Kopsavilkums</h2><div class="summary-row"><span>${c.seats.length} biļete(s)</span><strong>${money(c.subtotal)}</strong></div>${discount?`<div class="summary-row"><span>Atlaide</span><strong>−${discount}%</strong></div>`:''}<div class="summary-row total"><span>Kopā</span><span>${money(total)}</span></div><div class="form-grid"><label>E-pasts biļetei<input id="order-email" type="email" value="${state.profile?.email||''}" placeholder="vards@example.com"></label></div><div class="form-actions"><button class="button" data-action="checkout">Apstiprināt pirkumu</button></div></aside></section>`}
function ticket(){const o=view.order,m=movie(o.movieId),s=screening(o.screeningId),bits=Array.from({length:64},(_,i)=>((o.token.charCodeAt(i%o.token.length)+i)%3?'':'off'));return `<section><p class="eyebrow">Pirkums apstiprināts</p><h1 class="page-title">Digitālā biļete</h1><div class="ticket"><p class="eyebrow">KINO NOX · ${o.id}</p><h2>${m.title}</h2><div class="ticket-grid"><div><p><strong>${s.time}</strong> · ${s.hall}</p><p>Vietas: <strong>${o.seats.join(', ')}</strong></p><p class="meta">${o.email} · ${o.created}</p></div><div class="qr">${bits.map(c=>`<b class="${c}"></b>`).join('')}</div></div></div><div class="form-actions"><button class="button" data-nav="catalog">Atpakaļ uz katalogu</button><button class="button secondary" data-nav="profile">Mani pasūtījumi</button></div></section>`}
function profile(){const logged=state.profile;const orders=state.orders.filter(x=>!logged||x.email===logged.email);return `<section class="profile-layout"><div><p class="eyebrow">Profils</p><h1 class="page-title">${logged?logged.email:'Pieslēdzieties vai izveidojiet kontu.'}</h1>${logged?`<div class="panel"><h2>Mani pasūtījumi</h2>${orders.length?orders.map(o=>`<div class="admin-row"><span><strong>${movie(o.movieId).title}</strong><br><span class="meta">${o.created} · ${o.seats.join(', ')}</span></span><button class="button secondary" data-order="${o.id}">Biļete</button></div>`).join(''):'<p class="meta">Pasūtījumu vēl nav.</p>'}</div>`:`<p class="lede">Šis konts ir lokāls šajā pārlūkā. Neievadiet īstu paroli.</p>`}</div><aside class="panel">${logged?`<h2>Pieslēgts</h2><p class="meta">Konts un pasūtījumi glabājas tikai šajā pārlūkā.</p><button class="button secondary" data-action="logout">Iziet</button>`:`<h2>Izveidot vai atvērt profilu</h2><div class="form-grid"><label>E-pasts<input id="profile-email" type="email" placeholder="vards@example.com"></label><label>Mācību parole<input id="profile-password" type="password" placeholder="Vismaz 6 rakstzīmes"></label></div><div class="form-actions"><button class="button" data-action="register">Izveidot kontu</button><button class="button secondary" data-action="login">Pieslēgties</button></div>${view.notice?notice(view.notice):''}`}</aside></section>`}
function admin(){return `<section class="admin-layout"><div><p class="eyebrow">Operatora panelis</p><h1 class="page-title">Mācību dati</h1><p class="lede">Izmaiņas uzreiz saglabājas šajā pārlūkā. Izmantojiet atiestatīšanu, lai atgrieztu sākuma variantu.</p><div class="panel"><h2>Filmas</h2><div class="admin-list">${state.movies.map(m=>`<div class="admin-row"><span><strong>${m.title}</strong><br><span class="meta">${m.genre} · ${m.duration} min</span></span><button class="button secondary" data-movie="${m.id}">Skatīt</button></div>`).join('')}</div></div><div class="panel"><h2>Aktīvie seansi</h2><div class="admin-list">${state.screenings.map(s=>`<div class="admin-row"><span><strong>${movie(s.movieId).title}</strong><br><span class="meta">${s.time} · ${s.hall} · ${money(s.price)}</span></span></div>`).join('')}</div></div></div><aside><div class="panel"><h2>Pievienot filmu</h2><div class="form-grid"><label>Nosaukums<input id="new-title" placeholder="Filmas nosaukums"></label><label>Žanrs<input id="new-genre" placeholder="Žanrs"></label><label>Ilgums minūtēs<input id="new-duration" type="number" min="1" value="100"></label><label>Apraksts<textarea id="new-description" placeholder="Īss apraksts"></textarea></label></div><div class="form-actions"><button class="button" data-action="add-movie">Pievienot</button></div>${view.notice?notice(view.notice):''}</div><div class="panel"><h2>Mācību vide</h2><p class="meta">Šeit var mainīt datus un pēc tam pārbaudīt, vai katalogs, seansi un cenas attēlojas konsekventi.</p><button class="button danger" data-action="reset">Atiestatīt visus datus</button></div></aside></section>`}
function notice(n,type=''){return `<div class="notice ${type}">${n}</div>`}function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view.screen));let html=view.screen==='catalog'?catalog():view.screen==='movie'?movieDetail():view.screen==='booking'?booking():view.screen==='cart'?cart():view.screen==='ticket'?ticket():view.screen==='profile'?profile():admin();app.innerHTML=html;updateCart()}
function addCart(){const s=screening(view.screeningId);view.cart={movieId:s.movieId,screeningId:s.id,seats:[...view.seats],subtotal:view.seats.length*s.price,promo:''};view.screen='cart';view.notice=null;render()}
function checkout(){const email=document.querySelector('#order-email').value.trim();if(!/^\S+@\S+\.\S+$/.test(email)){toast('Ievadiet derīgu e-pasta adresi.');return}const c=view.cart;const taken=reserved(c.screeningId);if(c.seats.some(x=>taken.includes(x))){toast('Kāda vieta vairs nav pieejama. Atgriezieties pie seansa.');return}state.reserved[c.screeningId]=[...taken,...c.seats];const o={id:'KN-'+String(Date.now()).slice(-6),movieId:c.movieId,screeningId:c.screeningId,seats:c.seats,email,created:new Date().toLocaleString('lv-LV'),token:Math.random().toString(36).slice(2,10).toUpperCase()};state.orders.push(o);save();view={screen:'ticket',order:o,filter:view.filter};render()}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-movie],[data-show],[data-seat],[data-filter],[data-order]');if(!b)return;if(b.dataset.nav)return nav(b.dataset.nav);if(b.dataset.action==='home')return nav('catalog');if(b.dataset.filter){view.filter=b.dataset.filter;return render()}if(b.dataset.movie){view.screen='movie';view.movieId=Number(b.dataset.movie);return render()}if(b.dataset.show){view.screen='booking';view.screeningId=Number(b.dataset.show);view.seats=[];return render()}if(b.dataset.seat){const n=b.dataset.seat;view.seats=view.seats.includes(n)?view.seats.filter(x=>x!==n):[...view.seats,n];return render()}if(b.dataset.action==='add-cart')return addCart();if(b.dataset.action==='promo'){view.cart.promo=document.querySelector('#promo').value.trim();return render()}if(b.dataset.action==='checkout')return checkout();if(b.dataset.action==='register'||b.dataset.action==='login'){const email=document.querySelector('#profile-email').value.trim(),pass=document.querySelector('#profile-password').value;if(!/^\S+@\S+\.\S+$/.test(email)||pass.length<6){view.notice='Ievadiet derīgu e-pastu un vismaz 6 rakstzīmju mācību paroli.';return render()}let u=state.users.find(x=>x.email.toLowerCase()===email.toLowerCase());if(b.dataset.action==='register'&&!u){u={email,password:pass};state.users.push(u)}if(!u||u.password!==pass){view.notice='E-pasts vai mācību parole nav pareiza.';return render()}state.profile={email:u.email};save();view.notice=null;return render()}if(b.dataset.action==='logout'){state.profile=null;save();return nav('profile')}if(b.dataset.action==='add-movie'){const title=document.querySelector('#new-title').value.trim(),genre=document.querySelector('#new-genre').value.trim(),duration=Number(document.querySelector('#new-duration').value),description=document.querySelector('#new-description').value.trim();if(!title||!genre||!duration){view.notice='Aizpildiet nosaukumu, žanru un ilgumu.';return render()}state.movies.push({id:Math.max(...state.movies.map(x=>x.id))+1,title,genre,year:new Date().getFullYear(),duration,age:'7+',language:'Latviešu',subtitles:'Nav',price:8,accent:'linear-gradient(135deg,#243142,#5f7289)',description:description||'Mācību filmas apraksts.'});save();view.notice='Filma ir pievienota lokālajiem datiem.';return render()}if(b.dataset.action==='reset'){state=clone(seed);localStorage.removeItem(KEY);view={screen:'catalog',movieId:null,screeningId:null,seats:[],cart:null,filter:'Visi',notice:null};toast('Mācību dati ir atiestatīti.');return render()}if(b.dataset.order){const o=state.orders.find(x=>x.id===b.dataset.order);view={screen:'ticket',order:o,filter:view.filter};return render()}});
render();
